key: $BOT_WALLET_PRIVATEKEY
mnemonic: $MNEMONIC
walletCount: $WALLET_COUNT
topupAmount: $TOPUP_AMOUNT
rpc: $RPC_URL
writeRpc: $WRITE_RPC
subgraph: $SUBGRAPH
contracts:
  v4:
    sushiArbAddress: $ARB_ADDRESS
    genericArbAddress: $GENERIC_ARB_ADDRESS
    balancerArbAddress: $BALANCER_ARB_ADDRESS
    dispair: $DISPAIR
  v5:
    sushiArbAddress: $ARB_ADDRESS_V5
    genericArbAddress: $GENERIC_ARB_ADDRESS_V5
    balancerArbAddress: $BALANCER_ARB_ADDRESS_V5
    dispair: $DISPAIR_V5
liquidityProviders: $LIQUIDITY_PROVIDERS
route: $ROUTE
sleep: $SLEEP
poolUpdateInterval: $POOL_UPDATE_INTERVAL
gasCoveragePercentage: $GAS_COVER
txGas: $TX_GAS
quoteGas: $QUOTE_GAS
botMinBalance: $BOT_MIN_BALANCE
gasPriceMultiplier: $GAS_PRICE_MULTIPLIER
gasLimitMultiplier: $GAS_LIMIT_MULTIPLIER
timeout: $TIMEOUT
maxRatio: $MAX_RATIO
rpOnly: $RP_ONLY
ownerProfile: $OWNER_PROFILE
selfFundVaults: $SELF_FUND_ORDERS
sgFilter:
  includeOrders: $INCLUDE_ORDERS
  excludeOrders: $EXCLUDE_ORDERS
  includeOwners: $INCLUDE_OWNERS
  excludeOwners: $EXCLUDE_OWNERS
  includeOrderbooks: $INCLUDE_ORDERBOOKS
  excludeOrderbooks: $EXCLUDE_ORDERBOOKS
