name: Docker image CI

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to give the build. Try to make it unique.'
        required: true

env:
  CHANNEL: ${{ inputs.tag || github.head_ref || github.ref_name }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  TAG_BASE: rainprotocol/arb-bot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: cachix/cachix-action@v15
        continue-on-error: true
        with:
          name: rainlanguage
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: false
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 10G

      - name: Prepare Sushi Lib
        run: ./prep-sushi.sh

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build -t "$TAG_BASE:$CHANNEL" --build-arg GIT_SHA=${{ github.sha }} --build-arg DOCKER_CHANNEL=$CHANNEL .
      - run: |
          docker push "$TAG_BASE:$CHANNEL"