name: Standard Test
on: [push]

concurrency:
  group: ${{ github.ref }}-rainix
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit-test:
    permissions:
      id-token: write
      contents: write
    name: unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: cachix/cachix-action@v15
        continue-on-error: true
        with:
          name: rainlanguage
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: false
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 10G

      - name: Prepare Sushi Lib
        run: ./prep-sushi.sh

      - name: Install Dependencies
        run:  nix develop -c npm install

      - name: Lint
        run:  nix develop -c npm run lint
      
      - name: Run Tests
        run: nix develop -c npm run unit-test
  
  e2e-test:
    name: e2e fork test
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: [POLYGON, ARBITRUM, ETH, FLARE, BSC, BASE, LINEA]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: cachix/cachix-action@v15
        continue-on-error: true
        with:
          name: rainlanguage
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: false
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 10G

      - name: Prepare Sushi Lib
        run: ./prep-sushi.sh

      - name: Install Dependencies
        run:  nix develop -c npm install

      - name: Restore Hardhat Fork Cache
        uses: actions/cache@v6
        with:
          path: cache
          key: hardhat-fork-cache-${{ matrix.chain }}-${{ hashFiles('hardhat.config.ts') }}
          restore-keys: |
            hardhat-fork-cache-${{ matrix.chain }}-

      - name: Set Chain Rpc Key
        run: echo "RPC=CI_DEPLOY_${{ matrix.chain }}_RPC_URL" >> $GITHUB_ENV
      
      - name: Run Tests
        run: TEST_${{ matrix.chain }}_RPC=${{ secrets[env.RPC] }} nix develop -c npm run e2e-test
        env: 
          DEFAULT_RPC: ${{ secrets[env.RPC] }}